### ISSUE TITLE
Add LICENSE?

### ISSUE THREAD

**Issue by 0rphee** [Ksound22/developer-portfolio#11]
Hi @Ksound22 ! great article and repo. Just to be sure, is it okay to use the code from the repo? There is no license and in most countries that means completely proprietary code. Adding a license would ensure that using the code is fine (if that's what you want). Thank you in advance!

**Comment by Ksound22** [comment]
Hi @0rphee It's okay to use the code.

I will go ahead and add a license.

**Comment by 0rphee** [comment]
Thank you, have a great day!
